
spring:
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/aegis?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&charset=utf8
    username: yuzhou
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: AegisHikariCP
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 5
      idle-timeout: 600000

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1


  #  redis:
  #    database: 0
  #    timeout: 1000
  #    host: 192.168.0.106
  #    port: 6379
  #    password:
  #    # 连接池最大连接数（使用负值表示没有限制）
  #    jedis:
  #      pool:
  #        max-active: 100
  #        max-wait: 100
  #        max-idle: 90
  #        min-idle: 0
  #  data:
  #    mongodb:
  #      uri: mongodb://localhost:27017/legion

  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
    job-store-type: jdbc
    auto-startup: true
    startup-delay: 5s
    wait-for-jobs-to-complete-on-shutdown: true

  mail:
    host: smtp.qq.com
    username: 351975711@qq.com
    password: lolxhpfpcplobjdj
    default-encoding: UTF-8
    port: 465
    protocol: smtps
  thymeleaf:
    cache: false
    encoding: UTF-8



mybatis:
  mapper-locations: classpath*:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

