CREATE TABLE AC_ROLE
(
    ID           VARCHAR(8) PRIMARY KEY,
    ROLE_NAME    VARCHAR(32)  NOT NULL,
    TYPE         CHAR(3)      NOT NULL,
    DESCRIPTION  VARCHAR(100),
    IS_SYSTEM    CHAR(1),
    LANDING_PAGE VARCHAR(512) NOT NULL,
    CREATED_AT   DATETIME     NOT NULL,
    CREATED_BY   VARCHAR(32)  NOT NULL,
    UPDATED_AT   DATETIME     NOT NULL,
    UPDATED_BY   VARCHAR(32)  NOT NULL
);

INSERT INTO AC_ROLE (ID, ROLE_NAME, TYPE, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('SYSADMIN', 'System Administrator', 'SYS', 'Y', '/web/SystemIndex', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ID, ROLE_NAME, TYPE, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('DEV', 'Developer', 'DEV', 'N', '/web/index', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ID, ROLE_NAME, TYPE, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('QA', 'Quality Assurance', 'DEV', 'N', '/web/index', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ID, ROLE_NAME, TYPE, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('PJTADM', 'Project Administrator', 'ADM', 'N', '/web/index', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO AC_ROLE (ID, ROLE_NAME, TYPE, IS_SYSTEM, LANDING_PAGE, CREATED_AT, CREATED_BY,
                     UPDATED_AT, UPDATED_BY)
VALUES ('EXTPTY', 'External Party', 'USER', 'N', '/web/index', NOW(), 'SYSTEM', NOW(), 'SYSTEM');


