CREATE TABLE CM_ISSUE_RESOLUTION
(
    RESOLUTION_CODE VARCHAR(16) PRIMARY KEY,
    DISPLAY_NAME    VARCHAR(64) NOT NULL,
    DESCRIPTION     VARCHAR(500),
    IS_SYSTEM       CHAR(1)     NOT NULL,
    IS_INUSE        CHAR(1) DEFAULT 'Y',
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL
);