CREATE TABLE CM_ISSUE_STATUS
(
    STATUS_CODE  VARCHAR(16) PRIMARY KEY,
    DISPLAY_NAME VARCHAR(64) NOT NULL,
    DESCRIPTION  VARCHAR(500),
    COLOR        VARCHAR(7)  NOT NULL,
    IS_SYSTEM    CHAR(1)     NOT NULL,
    IS_INUSE     CHAR(1) DEFAULT 'Y',
    CREATED_AT   DATETIME    NOT NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    UPDATED_AT   DATETIME    NOT NULL,
    UPDATED_BY   VARCHAR(32) NOT NULL

);

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUE ('OPEN', '新问题', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');


INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('REOPEN', '复现（未修复）', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('INVEST', '正在查明原因', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('ACK', '问题已确认', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('COMMITTED', '已提交仓库', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('P_DEPLOY', '等待部署', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('DEPLOYED', '已部署', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('MONITOR', '监控中', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('FIX_VERIFIED', '修复已验证', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('P_EXT_PARTY', '等待外部确认', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('P_CONFIRM', '等待确认', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_STATUS (STATUS_CODE, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('CLOSED', '已关闭', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');


