CREATE TABLE CM_ISSUE_RESOLUTION
(
    RESOLUTION_CODE VARCHAR(16) PRIMARY KEY,
    DISPLAY_NAME    VARCHAR(64) NOT NULL,
    DESCRIPTION     VARCHAR(500),
    IS_SYSTEM       CHAR(1)     NOT NULL,
    IS_INUSE        CHAR(1) DEFAULT 'Y',
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL
);

INSERT INTO CM_ISSUE_RESOLUTION (RESOLUTION_CODE, DISPLAY_NAME, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('RESOLVED', '已解决', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_RESOLUTION (RESOLUTION_CODE, DISPLAY_NAME, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('RESOLVING', '正在解决', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_RESOLUTION (RESOLUTION_CODE, DISPLAY_NAME, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('POSTPONE', '推迟处理', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_RESOLUTION (RESOLUTION_CODE, DISPLAY_NAME, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('NOT_PROCEED', '暂不处理', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_RESOLUTION (RESOLUTION_CODE, DISPLAY_NAME, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('UNSOLVABLE', '无法处理', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

INSERT INTO CM_ISSUE_RESOLUTION (RESOLUTION_CODE, DISPLAY_NAME, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
    VALUE ('NO_NEED', '无需处理', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');

