CREATE TABLE CM_ISSUE_STATUS
(
    ISSUE_STATUS VARCHAR(16) PRIMARY KEY,
    DISPLAY_NAME VARCHAR(64) NOT NULL,
    DESCRIPTION  VARCHAR(500),
    COLOR        VARCHAR(7)  NOT NULL,
    IS_SYSTEM    CHAR(1)     NOT NULL,
    CREATED_AT   DATETIME    NOT NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    UPDATED_AT   DATETIME    NOT NULL,
    UPDATED_BY   VARCHAR(32) NOT NULL

);

INSERT INTO CM_ISSUE_STATUS (ISSUE_STATUS, DISPLAY_NAME, COLOR, IS_SYSTEM, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUE ('OPEN', '新问题', '#FFFFFF', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');