CREATE TABLE CM_SEQUENCE
(
    NAME        VARCHAR(32) PRIMARY KEY,
    VALUE       BIGINT      NOT NULL DEFAULT 0,
    MIN_VALUE   BIGINT      NOT NULL DEFAULT 0,
    MAX_VALUE   BIGINT,
    STEP        INT         NOT NULL DEFAULT 1,
    DESCRIPTION VARCHAR(100),
    CREATED_AT  DATETIME    NOT NULL,
    CREATED_BY  VARCHAR(32) NOT NULL,
    UPDATED_AT  DATETIME    NOT NULL,
    UPDATED_BY  VARCHAR(32) NOT NULL
);
