CREATE TABLE GNL_TIMESHEET
(
    ID                 BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ACCT_ID       BIGINT       NOT NULL,
    EVENT_REFERRAL_TBL VARCHAR(128) NOT NULL,
    EVENT_REFERRAL_ID  BIGINT       NOT NULL,
    IS_AUTO_ADDED      CHAR(1)      NOT NULL,
    CREATED_AT         DATETIME     NOT NULL,
    CREATED_BY         VARCHAR(32)  NOT NULL,
    UPDATED_AT         DATETIME     NOT NULL,
    UPDATED_BY         VARCHAR(32)  NOT NULL
);

CREATE TABLE GNL_COMMON_EVENT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(100) NOT NULL,
    TYPE        VARCHAR(16)  NOT NULL,
    CONTENT     VARCHAR(500),
    START_AT    DATETIME     NOT NULL,
    END_AT      DATETIME,
    COLOR       VARCHAR(7)   NOT NULL,
    TEXT_COLOR  VARCHAR(7)   NOT NULL,
    IS_ALL_DAY  CHAR(1)      NOT NULL,
    IS_EDITABLE CHAR(1)      NOT NULL,
    CREATED_AT  DATETIME     NOT NULL,
    CREATED_BY  VARCHAR(32)  NOT NULL,
    UPDATED_AT  DATETIME     NOT NULL,
    UPDATED_BY  VARCHAR(32)  NOT NULL
);
