CREATE TABLE GNL_EMAIL
(
    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    SUBJECT           VARCHAR(100),
    CONTENT           MEDIUMBLOB,
    IS_HAS_ATTACHMENT CHAR(1)     NOT NULL,
    CREATED_AT        DATETIME    NOT NULL,
    CREATED_BY        VARCHAR(32) NOT NULL,
    UPDATED_AT        DATETIME    NOT NULL,
    UPDATED_BY        VARCHAR(32) NOT NULL
);


CREATE TABLE GNL_EMAIL_ATTACHMENT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_ID    BIGINT       NOT NULL,
    FILE_NAME   VARCHAR(128) NOT NULL,
    FILE_NET_ID BIGINT       NOT NULL,
    CREATED_AT  DATETIME     NOT NULL,
    CREATED_BY  VARCHAR(32)  NOT NULL,
    UPDATED_AT  DATETIME     NOT NULL,
    UPDATED_BY  VARCHAR(32)  NOT NULL
);

ALTER TABLE GNL_EMAIL_ATTACHMENT
    ADD CONSTRAINT GNL_EMAIL_ATTACHMENT_FK1 FOREIGN KEY (EMAIL_ID) REFERENCES GNL_EMAIL (ID);



CREATE TABLE GNL_EMAIL_REPLY
(
    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_ID          BIGINT      NOT NULL,
    CONTENT           MEDIUMBLOB,
    IS_HAS_ATTACHMENT CHAR(1)     NOT NULL,
    CREATED_AT        DATETIME    NOT NULL,
    CREATED_BY        VARCHAR(32) NOT NULL,
    UPDATED_AT        DATETIME    NOT NULL,
    UPDATED_BY        VARCHAR(32) NOT NULL
);

CREATE TABLE GNL_EMAIL_OUTBOX
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_ID   BIGINT      NOT NULL,
    SENDER     VARCHAR(32) NOT NULL,
    STATUS     VARCHAR(16) NOT NULL,
    RECIPIENT  TEXT        NOT NULL,
    CREATED_AT DATETIME    NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    UPDATED_AT DATETIME    NOT NULL,
    UPDATED_BY VARCHAR(32) NOT NULL

);
ALTER TABLE GNL_EMAIL_OUTBOX ADD CONSTRAINT GNL_EMAIL_OUTBOX_FK1 FOREIGN KEY (EMAIL_ID) REFERENCES GNL_EMAIL(ID);

CREATE TABLE GNL_EMAIL_INBOX
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_ID       BIGINT      NOT NULL,
    RECIPIENT      VARCHAR(32) NOT NULL,
    RECIPIENT_TYPE VARCHAR(16) NOT NULL,
    IS_READ        CHAR(1)     NOT NULL,
    STATUS         VARCHAR(16) NOT NULL,
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL,
    INDEX GNL_EMAIL_INBOX_IDX1(RECIPIENT),
    UNIQUE GNL_EMAIL_INBOX_UK1(EMAIL_ID, RECIPIENT)

);
ALTER TABLE GNL_EMAIL_INBOX ADD CONSTRAINT GNL_EMAIL_INBOX_FK1 FOREIGN KEY (EMAIL_ID) REFERENCES GNL_EMAIL(ID);

CREATE TABLE GNL_EMAIL_REPLY_OUTBOX
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_REPLY_ID BIGINT      NOT NULL,
    SENDER         VARCHAR(32) NOT NULL,
    STATUS         VARCHAR(16) NOT NULL,
    RECIPIENT      TEXT        NOT NULL,
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL

);
ALTER TABLE GNL_EMAIL_REPLY_OUTBOX
    ADD CONSTRAINT GNL_EMAIL_REPLY_OUTBOX_FK1 FOREIGN KEY (EMAIL_REPLY_ID) REFERENCES GNL_EMAIL_REPLY (ID);

CREATE TABLE GNL_EMAIL_REPLY_INBOX
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_REPLY_ID BIGINT      NOT NULL,
    RECIPIENT      VARCHAR(32) NOT NULL,
    RECIPIENT_TYPE VARCHAR(16) NOT NULL,
    IS_READ        CHAR(1)     NOT NULL,
    STATUS         VARCHAR(16) NOT NULL,
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL,
    INDEX GNL_EMAIL_REPLY_INBOX_IDX1 (RECIPIENT),
    UNIQUE GNL_EMAIL_INBOX_UK1(EMAIL_REPLY_ID, RECIPIENT)
);

CREATE TABLE GNL_EMAIL_REPLY_ATTACHMENT
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL_REPLY_ID BIGINT       NOT NULL,
    FILE_NAME      VARCHAR(128) NOT NULL,
    FILE_NET_ID    BIGINT       NOT NULL,
    CREATED_AT     DATETIME     NOT NULL,
    CREATED_BY     VARCHAR(32)  NOT NULL,
    UPDATED_AT     DATETIME     NOT NULL,
    UPDATED_BY     VARCHAR(32)  NOT NULL
);
ALTER TABLE GNL_EMAIL_REPLY_ATTACHMENT
    ADD CONSTRAINT EMAIL_REPLY_ID_FK FOREIGN KEY (EMAIL_REPLY_ID) REFERENCES GNL_EMAIL_REPLY (ID);