CREATE TABLE ISU_ISSUE
(
    ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_ISSUE_ID      BIGINT       NOT NULL,
    MODULE_ID             BIGINT       NOT NULL,
    SUB_PROJECT_ID        BIGINT       NOT NULL,
    PROJECT_ID            BIGINT       NOT NULL,
    TITLE                 VARCHAR(100) NOT NULL,
    DESCRIPTION           MEDIUMBLOB   NOT NULL,
    REPRODUCIBILITY       VARCHAR(16)  NOT NULL,
    STATUS                VARCHAR(16)  NOT NULL,
    RESOLUTION            VARCHAR(16)  NOT NULL,
    PRIORITY              INT          NOT NULL,
    SEVERITY              INT          NOT NULL,
    CURRENTLY_ASSIGNED_TO BIGINT,
    ROOT_CAUSE            VARCHAR(4000),
    FIXED_AT              DATETIME,
    TAG                   VARCHAR(4000),
    CREATED_AT            DATETIME     NOT NULL,
    CREATED_BY            VARCHAR(32)  NOT NULL,
    UPDATED_AT            DATETIME     NOT NULL,
    UPDATED_BY            VARCHAR(32)  NOT NULL

);

CREATE TABLE ISU_ISSUE_HISTORY
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    ISSUE_ID   BIGINT,
    FIELD_NAME VARCHAR(64)  NOT NULL,
    OLD_VALUE  VARCHAR(128) NOT NULL,
    NEW_VALUE  VARCHAR(128) NOT NULL,
    CREATED_AT DATETIME     NOT NULL,
    CREATED_BY VARCHAR(32)  NOT NULL,
    UPDATED_AT DATETIME     NOT NULL,
    UPDATED_BY VARCHAR(32)  NOT NULL
);
ALTER TABLE ISU_ISSUE_HISTORY
    ADD CONSTRAINT ISU_ISSUE_HISTORY_FK FOREIGN KEY (ISSUE_ID) REFERENCES ISU_ISSUE (ID);

CREATE TABLE ISU_ATTACHMENT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    ISSUE_ID    BIGINT       NOT NULL,
    FILE_NAME   VARCHAR(128) NOT NULL,
    DOCUMENT_ID BIGINT       NOT NULL,
    CREATED_AT  DATETIME     NOT NULL,
    CREATED_BY  VARCHAR(32)  NOT NULL,
    UPDATED_AT  DATETIME     NOT NULL,
    UPDATED_BY  VARCHAR(32)  NOT NULL
);
ALTER TABLE ISU_ATTACHMENT
    ADD CONSTRAINT ISU_ATTACHMENT_FK FOREIGN KEY (ISSUE_ID) REFERENCES ISU_ISSUE (ID);

CREATE TABLE ISU_NOTE
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    ISSUE_ID   BIGINT      NOT NULL,
    CONTENT    MEDIUMBLOB  NOT NULL,
    TYPE       VARCHAR(8)  NOT NULL,
    CREATED_AT DATETIME    NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    UPDATED_AT DATETIME    NOT NULL,
    UPDATED_BY VARCHAR(32) NOT NULL
);
ALTER TABLE ISU_NOTE
    ADD CONSTRAINT ISU_NOTE_FK FOREIGN KEY (ISSUE_ID) REFERENCES ISU_ISSUE (ID);

CREATE TABLE ISU_RELATIONSHIP
(

    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    SRC_ISSUE_ID      BIGINT      NOT NULL,
    DEST_ISSUE_ID     BIGINT      NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(16) NOT NULL,
    CREATED_AT        DATETIME    NOT NULL,
    CREATED_BY        VARCHAR(32) NOT NULL,
    UPDATED_AT        DATETIME    NOT NULL,
    UPDATED_BY        VARCHAR(32) NOT NULL
);

CREATE TABLE ISU_TAG
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(64) NOT NULL,
    TYPE       CHAR(3)     NOT NULL,
    STATUS     VARCHAR(8)  NOT NULL,
    CREATED_AT DATETIME    NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    UPDATED_AT DATETIME    NOT NULL,
    UPDATED_BY VARCHAR(32) NOT NULL
);