CREATE TABLE PJT_PROJECT
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME           VARCHAR(64) NOT NULL UNIQUE,
    TYPE           CHAR(3)     NOT NULL,
    TYPE_OTHER     VARCHAR(100),
    DESCRIPTION    VARCHAR(4000),
    STATUS         VARCHAR(16) NOT NULL,
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL

);



CREATE TABLE PJT_MODULE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_ID  BIGINT,
    NAME        VARCHAR(64),
    DESCRIPTION VARCHAR(4000),
    CREATED_AT  DATETIME    NOT NULL,
    CREATED_BY  VARCHAR(32) NOT NULL,
    UPDATED_AT  DATETIME    NOT NULL,
    UPDATED_BY  VARCHAR(32) NOT NULL
);
ALTER TABLE PJT_MODULE ADD CONSTRAINT PJT_MODULE_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PJT_PROJECT(ID);

CREATE TABLE PJT_USER_PROJECT_ASN
(
    USER_ACCT_ID  BIGINT,
    PROJECT_ID    BIGINT,
    ASSIGN_REASON VARCHAR(4000),
    CREATED_AT    DATETIME    NOT NULL,
    CREATED_BY    VARCHAR(32) NOT NULL,
    UPDATED_AT    DATETIME    NOT NULL,
    UPDATED_BY    VARCHAR(32) NOT NULL
);