CREATE TABLE PJT_PROJECT_GROUP
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(64),
    DESCRIPTION VARCHAR(500),
    CREATED_AT  DATETIME    NOT NULL,
    CREATED_BY  VARCHAR(32) NOT NULL,
    UPDATED_AT  DATETIME    NOT NULL,
    UPDATED_BY  VARCHAR(32) NOT NULL

);

CREATE TABLE PJT_PROJECT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(64)   NOT NULL UNIQUE,
    GROUP_ID    BIGINT        NOT NULL,
    FILE_PATH   VARCHAR(4000) NOT NULL,
    IS_PUBLIC   CHAR(1)       NOT NULL DEFAULT 'N',
    DESCRIPTION VARCHAR(500),
    STAGE       CHAR(3),
    STATUS      VARCHAR(16)   NOT NULL,
    CREATED_AT  DATETIME      NOT NULL,
    CREATED_BY  VARCHAR(32)   NOT NULL,
    UPDATED_AT  DATETIME      NOT NULL,
    UPDATED_BY  VARCHAR(32)   NOT NULL

);
ALTER TABLE PJT_PROJECT
    ADD CONSTRAINT PJT_PROJECT_GROUP_FK FOREIGN KEY (GROUP_ID) REFERENCES PJT_PROJECT_GROUP (ID);


CREATE TABLE PJT_PROJECT_H
(
    AUDIT_ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE  CHAR(2),
    AUDIT_TIME  DATETIME,
    ID          BIGINT,
    NAME        VARCHAR(64),
    GROUP_ID    BIGINT,
    FILE_PATH   VARCHAR(4000),
    IS_PUBLIC   CHAR(1),
    DESCRIPTION VARCHAR(500),
    STAGE       CHAR(3),
    STATUS      VARCHAR(16),
    CREATED_AT  DATETIME,
    CREATED_BY  VARCHAR(32),
    UPDATED_AT  DATETIME,
    UPDATED_BY  VARCHAR(32)

);



CREATE TABLE PJT_MODULE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_ID  BIGINT,
    NAME        VARCHAR(64),
    DESCRIPTION VARCHAR(500),
    CREATED_AT  DATETIME    NOT NULL,
    CREATED_BY  VARCHAR(32) NOT NULL,
    UPDATED_AT  DATETIME    NOT NULL,
    UPDATED_BY  VARCHAR(32) NOT NULL
);
ALTER TABLE PJT_MODULE
    ADD CONSTRAINT PJT_MODULE_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PJT_PROJECT (ID);


CREATE TABLE PJT_USER_PROJECT_ASN
(
    USER_ACCT_ID  BIGINT NOT NULL,
    PROJECT_ID    BIGINT,
    GROUP_ID      BIGINT NOT NULL ,
    ASSIGN_REASON VARCHAR(500),
    CREATED_AT    DATETIME    NOT NULL,
    CREATED_BY    VARCHAR(32) NOT NULL,
    UPDATED_AT    DATETIME    NOT NULL,
    UPDATED_BY    VARCHAR(32) NOT NULL,
    UNIQUE (USER_ACCT_ID, PROJECT_ID, GROUP_ID)
);

CREATE TABLE PJT_USER_PROJECT_ASN_H
(
    AUDIT_ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUDIT_TYPE    CHAR(2),
    AUDIT_TIME    DATETIME,
    USER_ACCT_ID  BIGINT,
    PROJECT_ID    BIGINT,
    GROUP_ID      BIGINT,
    ASSIGN_REASON VARCHAR(500),
    CREATED_AT    DATETIME,
    CREATED_BY    VARCHAR(32),
    UPDATED_AT    DATETIME,
    UPDATED_BY    VARCHAR(32)
);
ALTER TABLE PJT_USER_PROJECT_ASN
    ADD CONSTRAINT PJT_USER_PROJECT_ASN_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PJT_PROJECT (ID);

ALTER TABLE PJT_USER_PROJECT_ASN
    ADD CONSTRAINT PJT_USER_PROJECT_ASN_USER_ID_FK FOREIGN KEY (USER_ACCT_ID) REFERENCES AC_USER_ACCT (ID);
