CREATE TABLE PJT_PROJECT
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME           VARCHAR(64) NOT NULL UNIQUE,
    TYPE           CHAR(3)     NOT NULL,
    TYPE_OTHER     VARCHAR(100),
    REQ_START_DATE DATE,
    REQ_END_DATE   DATE,
    DEV_START_DATE DATE,
    DEV_END_DATE   DATE,
    SIT_START_DATE DATE,
    SIT_END_DATE   DATE,
    UAT_START_DATE DATE,
    UAT_END_DATE   DATE,
    DESCRIPTION    VARCHAR(4000),
    STATUS         VARCHAR(16) NOT NULL,
    CREATED_AT     DATETIME    NOT NULL,
    CREATED_BY     VARCHAR(32) NOT NULL,
    UPDATED_AT     DATETIME    NOT NULL,
    UPDATED_BY     VARCHAR(32) NOT NULL

);



CREATE TABLE PJT_MODULE
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_ID  BIGINT,
    NAME        VARCHAR(64),
    DESCRIPTION VARCHAR(4000),
    CREATED_AT  DATETIME    NOT NULL,
    CREATED_BY  VARCHAR(32) NOT NULL,
    UPDATED_AT  DATETIME    NOT NULL,
    UPDATED_BY  VARCHAR(32) NOT NULL
);

CREATE TABLE PJT_USER_PROJECT_ASN
(
    USER_ACCT_ID  BIGINT,
    PROJECT_ID    BIGINT,
    ASSIGN_REASON VARCHAR(4000),
    CREATED_AT    DATETIME    NOT NULL,
    CREATED_BY    VARCHAR(32) NOT NULL,
    UPDATED_AT    DATETIME    NOT NULL,
    UPDATED_BY    VARCHAR(32) NOT NULL
);