CREATE TABLE SA_EMAIL_ARCHIVE
(
    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    SENT_FROM         VARCHAR(64)   NOT NULL,
    SENT_TO           VARCHAR(1024) NOT NULL,
    CC                VARCHAR(1024),
    SUBJECT           VARCHAR(500)  NOT NULL,
    CONTENT           MEDIUMBLOB,
    STATUS            VARCHAR(16)   NOT NULL,
    ATTACHMENT        MEDIUMBLOB,
    CREATED_AT        DATETIME      NOT NULL,
    CREATED_BY        VARCHAR(32)   NOT NULL,
    UPDATED_AT        DATETIME      NOT NULL,
    UPDATED_BY        VARCHAR(32)   NOT NULL
);



